/**
 * Ejemplo: Exportador personalizado - Mermaid Diagram
 * Genera diagramas Mermaid.js del grafo de dependencias
 * Útil para documentación en GitHub, Notion, Obsidian, etc.
 */

import type { ExporterPlugin, ExportData, ExportOptions } from '../index.ts';

const mermaidExporter: ExporterPlugin = {
  name: 'mermaid-diagram',
  description: 'Genera diagrama de dependencias en formato Mermaid.js',
  extension: 'mmd',
  mimeType: 'text/plain',
  export: async (data: ExportData, options: ExportOptions = {}): Promise<string> => {
    const { graph, projectName } = data;
    const groupByDirectory = options.groupByDirectory ?? false;

    let output = `%% Mermaid Diagram for ${projectName}\n`;
    output += `%% Generated by Code Graph Unified\n\n`;

    // Configuración del diagrama
    output += `graph TD\n`;

    // Definir nodos con estilos
    const nodeMap = new Map();
    let nodeIndex = 0;

    for (const node of graph.nodes) {
      const safeId = `n${nodeIndex++}`;
      nodeMap.set(node.id, safeId);

      // Estilo según tipo y errores
      let style = '';
      if (node.errors > 0) {
        style = ':::hasError';
      } else if (node.lang === 'TypeScript') {
        style = ':::ts';
      } else if (node.lang === 'JavaScript') {
        style = ':::js';
      } else if (node.lang === 'Python') {
        style = ':::py';
      }

      const label = node.name.length > 30 ? node.name.slice(0, 27) + '...' : node.name;
      output += `  ${safeId}[${label}]${style}\n`;
    }

    // Edges (dependencias internas)
    for (const edge of graph.edges) {
      const source = nodeMap.get(edge.source);
      const target = nodeMap.get(edge.target);

      if (source && target) {
        const style = edge.circular ? ' -.-> ' : ' --> ';
        output += `  ${source}${style}${target}\n`;
      }
    }

    // Definir estilos CSS
    output += `\n  classDef hasError fill:#ff6b6b,color:#fff,stroke:#fff;\n`;
    output += `  classDef ts fill:#3178c6,color:#fff;\n`;
    output += `  classDef js fill:#f7df1e,color:#333;\n`;
    output += `  classDef py fill:#3776ab,color:#fff;\n`;

    // Subgráficos por directorio (opcional)
    if (groupByDirectory) {
      const dirs = new Map();
      for (const node of graph.nodes) {
        const parts = node.path.split('/');
        if (parts.length > 1) {
          const dir = parts.slice(0, -1).join('/');
          if (!dirs.has(dir)) dirs.set(dir, []);
          dirs.get(dir).push(nodeMap.get(node.id));
        }
      }

      for (const [dir, nodes] of dirs) {
        if (nodes.length > 1) {
          output += `  subgraph "${dir}"\n`;
          for (const n of nodes) output += `    ${n}\n`;
          output += `  end\n`;
        }
      }
    }

    return output;
  },
};

export default mermaidExporter;
